[project]
name = "frontend"
version = "0.1.0"
description = "Frontend UI for clients of Volleyball Tracker"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "requests>=2.32.5",
    "streamlit>=1.54.0",
]
